SERVICE_FEE_PERCENT = 2

ADULT_PASSENGER_FARE = 200
SENIOR_CITIZEN_PASSENGER_FARE = 100
KID_PASSENGER_FARE = 50

AVAILABLE_STATIONS = ["CENTRAL", "AIRPORT"]

PASSENGERS_TYPES = {
    "ADULT": ADULT_PASSENGER_FARE,
    "SENIOR_CITIZEN": SENIOR_CITIZEN_PASSENGER_FARE,
    "KID": KID_PASSENGER_FARE,
}
