SERVICE_FEE_PERCENT = 2

ADULT_PASSENGER_FARE = 200
SENIOR_CITIZEN_PASSENGER_FARE = 100
KID_PASSENGER_FARE = 50

AVAILABLE_STATIONS = ["AIRPORT", "CENTRAL"]

PASSENGERS_TYPES = {
    "ADULT": 200,
    "SENIOR_CITIZEN": 100,
    "KID": 50,
}
